### ISSUE TITLE
Fuzzy matchers do not work with "anything" expectations when passed Java objects

### ISSUE THREAD

**Issue by asthasr** [rspec/rspec-support#159]
Originally, I left a issue on `rspec-mocks`, [Issue #877](https://github.com/rspec/rspec-mocks/issues/877). However, further investigation shows that the origin is actually in `rspec-support`, specifically in `FuzzyMatcher.values_match?`:

```ruby
def self.values_match?(expected, actual)
  if Array === expected && Enumerable === actual && !(Struct === actual)
    return arrays_match?(expected, actual.to_a)
  elsif Hash === expected && Hash === actual
    return hashes_match?(expected, actual)
  elsif actual == expected
    return true
  end

  begin
    expected === actual
  rescue ArgumentError
    # Some objects, like 0-arg lambdas on 1.9+, raise
    # ArgumentError for `expected === actual`.
    false
  end
end
```

Due to this code, using an `anything` matcher will always result in an error, because the `#==` method on the `actual` object will *not* match the `anything` matcher, which relies on its own `#===` method to return true in all cases.

Prior to this change, the `begin`/`rescue` block had an or clause:

```ruby
actual == expected || expected === actual
```

This would *still* be broken in some cases that raise argument errors, however, as well as in the case of JRuby, where `Foo.equals(RubyObject)` is always going to fail.

**Comment by benissimo** [comment]
Shouldn't this be `expected == actual` instead? Shouldn't the expected object call equals() and not the actual? That would solve the class casting issue (see rspec-mocks #877)

**Comment by myronmarston** [comment]
> Due to this code, using an anything matcher will always result in an error, because the #== method on the actual object will not match the anything matcher, which relies on its own #=== method to return true in all cases.

If `==` returns false, that's fine; in that case it gets down to `expected === actual` and `Anything#===` is defined to return `true` -- so that shouldn't be a problem.

Maybe I'm not understanding your issue correctly (which is quite likely, given my lack of JRuby experience...), but it looks like the problem is that `==` is raising an error rather than returning a boolean value.  This is a violation of the semantics RSpec expects for `==` -- `==` should return `false` if two objects are unequal, not raise an error.

> Prior to this change, the begin/rescue block had an or clause:

To what change are you referring?

> Shouldn't this be `expected == actual` instead? Shouldn't the expected object call `equals()` and not the actual? That would solve the class casting issue (see rspec-mocks #877)

`==` is supposed to be symmetric, where `a == b` and `b == a` return the same value, so in general it shouldn't matter, and in situations where it does, you're treading on brittle ground.  FWIW, the primary way `expected` is given to participate in determining if the objects match or not is `===`, which is decidedly _not_ symmetric, and _must_ be `expected === actual`.  When writing this logic, I chose to do `actual == expected` because it felt appropriate (at the time, anyway) that since we had called `===` on `expected`, we should balance it out and call `==` on `actual`.  Not that it should generally matter (given the intended symmetric property of `==`) and I can't think of a case that relies on it being `actual ==`, so I'm open to changing it.

The biggest thing we need now is a reproducible example so we can add a spec for this (see discussion on rspec/rspec-mocks#877).

**Comment by asthasr** [comment]
> Maybe I'm not understanding your issue correctly (which is quite likely, given my lack of JRuby experience...), but it looks like the problem is that == is raising an error rather than returning a boolean value. This is a violation of the semantics RSpec expects for == -- == should return false if two objects are unequal, not raise an error.

You're right; this is a flaw in the #equals method on the Java object (a `ClassCastException` is being thrown in Java). Argh. I'll close this. :)

**Comment by myronmarston** [comment]
> You're right; this is a flaw in the #equals method on the Java object (a ClassCastException is being thrown in Java). Argh. I'll close this. :)

I still think we can do something about this, if you can help come up with a reproducible example...

**Comment by asthasr** [comment]
It's our own fault. `equals` is not supposed to produce a `ClassCastException`, so writing code to mitigate it is unnecessary. In fact, due to the issue you found with the non-commutative nature of JRuby `==`, it's *better* for JRuby users that we try `javaObject.equals()` first... because that way, if a JRuby translation exists, it will get called, whereas `ruby_object == java_object` will not result in the same translation.

**Comment by myronmarston** [comment]
Gotcha. Thanks for following up!

**Comment by asthasr** [comment]
Yep! Sorry for the spurious issue. I'll try to contribute something as penance. :)
