### ISSUE TITLE
defining == method causes spec fail from Rspec3.2.0

### ISSUE THREAD

**Issue by curi1119** [rspec/rspec-support#170]
I have a class which defines method '=='.
When I use instance of that class as arguments and stub that method, RSpec3.2.0 fails.
There were no probelem at RSpec3.1.0.

I think this commit causes problem.
https://github.com/rspec/rspec-support/commit/c501d8d4debe749fc793053a6ba0e3a37d95554f#diff-85b7b238e0bce7105f1f3b1ee6ecf6ddR15

I uploaded codes which reproduce this issue.
https://github.com/curi1119/rspec_check

Is there any way to avoid this issue?
Or can you fix to work as 3.1.0?

Thank you.

**Comment by JonRowe** [comment]
So I looked at your code sample and the issue is your implementation of `==`, given that `==` is part of the standard Ruby protocol you need to protect against the case where the object passed in doesn't implement `x` and `y`, in this case it's being used to compare your object to one of our machers, an easy way to fix this in your case would be to add `return unless p.respond_to?(:x) && p.respond_to?(:y)`, that you didn't run into this in 3.1.x is purely coincidental.

**Comment by curi1119** [comment]
ok, thank you for your advice.
