### ISSUE TITLE
Fuzzing matching of DateTime

### ISSUE THREAD

**Issue by vovchynniko** [rspec/rspec-support#329]
Hello.

Please consider the following test example:

```
Wrapper = Struct.new(:date)
w = Wrapper.new(DateTime.new(2017, 9, 22, 20, 0, 30))

expect(w).not_to have_attributes(date: DateTime.new(2017, 9, 22, 15, 30, 15))
```

Unfortunately, this test will fail because `have_attributes` matcher internally uses `FuzzyMatcher` for comparing two dates which in turn uses `Date#===`. Since `DateTime` inherits from `Date` it uses this method which returns true for dates if they are the same day what is exactly we have in our example.

From the example shown above it was not obvious the datetimes would be compared as dates and this situation could potentially be dangerous for those who don't know about it.

EDIT: forgot to add `date:` to `have_attributes`

**Comment by myronmarston** [comment]
I don't understand your example.  `have_attributes` accepts a hash of key/value pairs, for what the attributes names and values are.  You've passed a `DateTime` that doesn't make any sense to me...

**Comment by vovchynniko** [comment]
This is the docs for `have_attributes` method from `rspec-expectations` method:
```
    # Passes if actual's attribute values match the expected attributes hash.
    # This works no matter how you define your attribute readers.
    #
    # @example
    #   Person = Struct.new(:name, :age)
    #   person = Person.new("Bob", 32)
    #
    #   expect(person).to have_attributes(:name => "Bob", :age => 32)
    #   expect(person).to have_attributes(:name => a_string_starting_with("B"), :age => (a_value > 30) )
    #
    # @note It will fail if actual doesn't respond to any of the expected attributes.
    #
    # @example
    #   expect(person).to have_attributes(:color => "red")
    def have_attributes(expected)
      BuiltIn::HaveAttributes.new(expected)
    end
    alias_matcher :an_object_having_attributes, :have_attributes
    alias_matcher :having_attributes,           :have_attributes
```

It works both for hashes and objects.

**Comment by vovchynniko** [comment]
Sorry, you're right I fixed my example but it still won't pass.

**Comment by myronmarston** [comment]
To support composable matchers, all our higher-order matchers (e.g. matchers which can accept other matchers, regexes, etc as arguments) use the `===` protocol for matching against the arguments.  This provides a lot of additional flexibility that many users rely on and it's not something we can consider changing at this point.  It's unfortunate that Ruby defines `DateTime#===` to only match on the date part of it.  IMO, that's very surprising behavior, to the point where it feels like a bug to me, although I suspect it was intentional.  If you agree, consider opening a bug with the ruby core team to see if they'll change it.

In the mean time, you can work around this by changing your expectation like so:

``` ruby
expect(w).not_to have_attributes(date: an_object_eq_to(DateTime.new(2017, 9, 22, 15, 30, 15)))
```

By wrapping it in `an_object_eq_to` (an alias of the `eq` matcher, which matches using `==`), your ensuring it only matches if the date times are exactly equal using `==`, rather than using the more lenient `===` method.

**Comment by vovchynniko** [comment]
Thank you, @myronmarston. I agree, this behaviour was really unexpected of DateTime but Ruby documentation specifically mentions the comparison of DateTime using `===`. Meanwhile I think I'll gonna use your workaround.
