### ISSUE TITLE
Why does `FuzzyMatcher.values_match` rely on `===` ?

### ISSUE THREAD

**Issue by smanolloff** [rspec/rspec-support#340]
Hi all! Like so many others, I have been using RSpec for years as my tool of choice for BDD -- it is the best out there for me.

But today I came upon a false positive illustrated with the below example:

```ruby
require 'date'
require 'active_support/core_ext/range/include_range'

RSpec.describe 'match_array' do
  it 'works with range values' do
    expect([1..2]).not_to contain_exactly([1..10])
  end
end
```

It apparently happens, because `contain_exactly` uses `===` to compare individual objects that have returned `false` for `==`, but respond to `to_a`. 

In this case, `Range#===` internally calls `include?`, which returns `true`. If we replace `contain_exactly` matcher with the `include` matcher, the situation is the same -- rspec thinks that `1..2` contains `1..10`. All because of [this](https://github.com/rspec/rspec-support/blob/cb038ded6e041b86213ecbd34b64fd138bc8ac65/lib/rspec/support/fuzzy_matcher.rb#L18).

Think about it -- the terms _contain exactly_ (hence, _match array_) are very misleading. The `===` method has nothing to do with _inclusion_, let alone _equality_. It can be used for all but _exact_ comparisons :).

One might object: "this works without the active support extensions". But isn't the code _behaviour_ 
 the thing we actually test, after all:  `1..2 does NOT include 1..10` is the correct behaviour. RSpec does not think so, because it actually tests if `1..10 === 1..2`. Totally not good.

What valid examples exist out there that support this unreliable check? For me, it makes sense to remove it and, if it must remain somewhere, let it be in a more appropriate matcher name.

**Comment by myronmarston** [comment]
In RSpec 3, we added support for [composing matchers](http://rspec.info/blog/2014/01/new-in-rspec-3-composable-matchers/), where you can pass one matcher to another.  This is quite useful, as it allows you to do things like:

``` ruby
expect(array).to contain_exactly(
  a_string_starting_with("foo"),
  a_string_starting_with("bar")
)
```

...which would match if `array` was `["food", "barn"]` or `["barge", "fool"]` or any number of other similar arrays.  It's worth noting that the term "exactly" in `contain_exactly` is meant to mean "contain just these items and no more", and is not meant to imply exact equality between the expected and actual items.  (Sorry if that's confusing; naming is hard!)

All the higher-order matchers (i.e. the ones that _accept_ matchers as arguments) delegate to `FuzzyMatcher.values_match?` to provide this feature.  When we implemented composable matchers, we decided to use `===` as the main protocol for it, for a couple reasons:

* It's a protocol that's built in to Ruby.  In general, in an expression like `a === b`, `a` defines a _category_ to which `b` might or might not belong -- and the `===` operator is used to check if it belongs to the category.  For example in `/warn/ === "warning"` returns true, because the regex `/warn/` defines a category to which the string "warning" belongs.  This protocol was a very natural fit for what we wanted to do with composable matchers.
* Some ruby objects (like regexes) already implement this protocol, so they can participate in this kind of fuzzy matching automatically.  In fact, RSpec already had special support for regexes for certain matchers, and when we moved to composable matchers using `===`, it allowed us to remove the special-case regex code while retaining support, since we were now using the general `===` protocol.

Unfortunately, `require 'active_support/core_ext/range/include_range'` makes `Range#===` act in a way that seems wrong to most people.  That happens because [`Range#===` delegates to `include?`](https://github.com/ruby/ruby/blob/v2_5_0/range.c#L1106-L1129)--a fact that the Rails maintainers may not have been aware of when they implemented that monkey patch.

If you have a case where you want strict matching semantics (such as this one), you can wrap any expected value with `an_object_eq_to` (which is an alias of `eq` designed to read more naturally in these situations):

``` ruby
RSpec.describe 'match_array' do
  it 'works with range values' do
    expect([1..2]).not_to contain_exactly(an_object_eq_to [1..10])
  end
end
```

`an_object_eq_to`/`eq` defines `===` to only return true when the underlying object returns true for `==`, so this'll do what you want.

> What valid examples exist out there that support this unreliable check?

See any of the examples in the composable matchers blog post.  Also, composable matchers have been out in the wild for ~3.5 years now and many users rely on it, so there are tons of valid examples out in the wild.  

> For me, it makes sense to remove it and, if it must remain somewhere, let it be in a more appropriate matcher name.

We're not going to remove `FuzzyMatcher` or its use of `===` (the entire reason it's called "fuzzy" matcher is that it fuzzy-matches with `===`!).  It's quite useful and many users rely on it at this point.

On a side note, this is the 2nd time in a week that problems from Rails' monkey patch to `Range` have come up (see rspec/rspec-expectations#1042), but I don't think it had come up before.  Kinda funny!
